name: tutorial
description: Multiple language Changer Application in Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.0
  get_storage: ^2.1.1
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/images/